algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var

arrayIdades: vetor [1..6] de inteiro;


inicio

arrayIdades[1] <- 1
arrayIdades[2] <- 36
escreva(arrayIdades[2]);

fimalgoritmo